[versions]
# Plugins
jdkprovider = "0.4.0"
cabe = "3.1.0"
spotbugs = "6.4.8"
jmh-gradle = "0.7.3"

# Dependencies
jspecify = "1.0.0"
slf4j = "2.0.17"
log4j = "2.25.3"
commons-logging = "1.3.5"
junit-bom = "6.0.1"
jmh = "1.37"
logback = "1.5.24"

[plugins]
jdkprovider = { id = "com.dua3.gradle.jdkprovider", version.ref = "jdkprovider" }
cabe = { id = "com.dua3.cabe", version.ref = "cabe" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh-gradle" }

[libraries]
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-jdk14 = { group = "org.slf4j", name = "slf4j-jdk14", version.ref = "slf4j" }
slf4j-jcl = { group = "org.slf4j", name = "jcl-over-slf4j", version.ref = "slf4j" }
slf4j-jul = { group = "org.slf4j", name = "jul-to-slf4j", version.ref = "slf4j" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core" }
log4j-bom = { group = "org.apache.logging.log4j", name = "log4j-bom", version.ref = "log4j" }
log4j-slf4j2 = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl" }
log4j-jcl = { group = "org.apache.logging.log4j", name = "log4j-jcl" }
log4j-jul = { group = "org.apache.logging.log4j", name = "log4j-jul" }
log4j-to-slf4j = { group = "org.apache.logging.log4j", name = "log4j-to-slf4j" }
commons-logging = { group = "commons-logging", name = "commons-logging", version.ref = "commons-logging" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-bom" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
jmh-core = { group = "org.openjdk.jmh", name = "jmh-core", version.ref = "jmh" }
jmh-generator = { group = "org.openjdk.jmh", name = "jmh-generator-annprocess", version.ref = "jmh" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
